# Chiavi API
[api_keys]
openai = "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"
google_maps = "la_tua_chiave_api_google_maps"

# Configurazione del database
[database]
host = "nome_host_del_database"
port = 5432
username = "nome_utente_database"
password = "password_database"
database_name = "nome_del_database"

# Altre configurazioni
[app]
debug_mode = true
secret_key = "una_chiave_segreta_molto_lunga_e_complessa"

# Credenziali per servizi esterni
[external_services]
email_sender = "il_tuo_indirizzo_email@esempio.com"
email_password = "la_tua_password_email"
